name: Synchronize
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  sync:
    name: Synchronize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Bun
        uses: oven-sh/setup-bun@v0.1.8
        with:
          bun-version: '0.5.4'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Synchronize messages
        run: bun scripts/sync-messages.ts
        env:
          RESOURCES_WEBHOOK_URL: ${{ secrets.RESOURCES_WEBHOOK_URL }}
          RULES_WEBHOOK_URL: ${{ secrets.RULES_WEBHOOK_URL }}
      - name: Synchronize teams
        run: bun scripts/sync-teams.ts
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: always()
        with:
          commit_message: Update state file
          commit_user_name: 'creatorsgarten[bot]'
          commit_user_email: 'creatorsgarten[bot]@users.noreply.github.com'
      - name: Dump the new state
        if: always()
        run: cat state.yml
