name: Synchronize
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  sync:
    name: Synchronize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Bun
        uses: oven-sh/setup-bun@v0.1.8
        with:
          bun-version: '0.5.8'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Preview teams
        run: bun scripts/sync-teams.ts
